"""make link_url optional in gifts

Revision ID: 95b093dfd0f7
Revises: 3c7616a4a365
Create Date: 2026-04-09 22:59:19.135958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '95b093dfd0f7'
down_revision: Union[str, Sequence[str], None] = '3c7616a4a365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gifts', 'link_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gifts', 'link_url',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500),
               nullable=False)
    # ### end Alembic commands ###
